### ISSUE TITLE
Works for me only if I add additional set of parentheses.

### ISSUE THREAD

**Issue by vi** [synek317/test-case-derive#2]
Like this:

```rust
    #[test_case((42))] 
    fn qqq(x:i32) {
        assert_eq!(x*x-1,(x+1)*(x-1)); 
    }
```

Otherwise fails [like on the build server](https://travis-ci.org/synek317/test-case-derive/builds/377591366).

**Comment by synek317** [comment]
It took me a long time, but I've just updated the code and it should now work well with newest rust nightly. Could you please try and confirm? @vi
