### ISSUE TITLE
What if function declaration is valid as well?

### ISSUE THREAD

**Issue by boncheolgu** [synek317/test-case-derive#3]
Here is a test case.
```
#[test_case(2, 4 => 6)]
fn add(x: i32, y: i32) -> i32 {
    x + y
}
```
However, I want to use `add` somewhere
```
fn main() {
    println!("{} + {} = {}", 2, 4, add(2, 4));
}
```
Thanks for the great crate!

**Comment by synek317** [comment]
I'm glad you like it :)

I must admit that your usecase is very interesting. I never thought about such use of `test_case` attribute.

It is intended to use in `#[cfg(test)]` code, e.g.

```
fn add(x: i32, y: i32) -> i32 {
    x + y
}

fn main() {
    println!("{} + {} = {}", 2, 4, add(2, 4));
}

#[cfg(test)]
mod tests {
    use test_case_derive::test_case;

    #[test_case(2, 4 => 6)]
    fn adds_correctly(x: i32, y: i32) -> i32 {
        add(x, y)
    }
}
```

Of course, for such a short and simple function it looks silly but most of the time the functions you test are more complicated and require some preparation of input or postprocessing of output before assert.
