### ISSUE TITLE
Fix names before 1.0

### ISSUE THREAD

**Issue by synek317** [synek317/test-case-derive#6]
There are two issues with names used in this crate:

1) crate name is `test-case-derive` but it provides attribute-like proc macro and not custom derive. This is misleading but I  have no idea how could I rename the whole crate

2) macro name is `test_case`. This name is used in the stdlib: https://github.com/rust-lang/rust/issues/50297 (it was not used at the time when I created this crate). I think it may cause problems when std::test_case becomes more popular. Do you have any good proposal for a different name?

**Comment by frehberg** [comment]
As for the crate-name, I am maintaining https://crates.io/crates/test-generator, which is handling generic test cases over filesystem-entities and  also values-sets, but not as nice as your solution. My plan was to reduce the focus of my crate onto  "generic test cases over filesystem entities" and use your crate test-case-derive for generic test-cases over values. 
Now, if you aren't  happy with the crate name "test-case-derive", I would be pleased to join forces and offering  the crate name "test-generator".
Please let me know, Kind regards, Frank

**Comment by synek317** [comment]
https://github.com/frondeus/test-case solves it
